global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'Flink'
    static_configs:
      - targets: [
        'host.docker.internal:9249',
        'host.docker.internal:9250'
      ]
  - job_name: 'Kafka'
    static_configs:
      - targets: [ 'host.docker.internal:9944' ]
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ['host.docker.internal:9093']